services:
  php:
    build:
      context: .
      dockerfile: ./docker/php-fpm/Dockerfile
    volumes:
      - ./public:/var/www/html/public
      - ./src:/var/www/html/src
      - ./vendor:/var/www/html/vendor
      - ./:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - mysql
      - redis
      - rabbitmq
    container_name: symfony-php-container
    networks:
      - app_network
    command: sh -c "composer install --no-interaction && \
      php bin/console doctrine:schema:update --force && \
      php bin/console doctrine:fixtures:load --no-interaction && \
      php-fpm -D && \
      supercronic /etc/crontab"

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    container_name: symfony-nginx-container
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    container_name: symfony-mysql-container
    networks:
      - app_network

  redis:
    image: redis:alpine
    container_name: symfony-redis-container
    ports:
      - "6379:6379"
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: symfony-rabbitmq-container
    ports:
      - "5672:5672"  # RabbitMQ service
      - "15672:15672"  # Management interface
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app_network

volumes:
  mysql_data:

networks:
  app_network:
    driver: bridge